### PR TITLE
Bash Completion for ModelSEED

### PR DESCRIPTION
**Pull request by devoid**
- script generateBashCompletionRules that generates
  rules for bash completion. These are put into the
  module:
- ModelSEED::Bash::Completion::Rules, a module with
  rules for doing bash completion. This is read in
  by the bash completion plugin:
- Bash::Completion::Plugins::ModelSEED, a plugin
  that is initialized by the Bash::Completion stuff.

To use, add `source setup-bash-complete` to your
.bashrc or .bash_profile...

TODO :
- implement options that consume args, e.g. --with foo
- implement completion for arguments, e.g. ms list <TAB>
- more unit tests, figure out how to do this properly

### CODE REVIEW

**Comment by cshenry** [comment]
I checked this out, but even after running carton install, I still couldn't run source setup-bach-complete. Where is that sh file?

**Comment by devoid** [comment]
1. It's `setup-bash-complete` for BourneAgainSHell
2. If you installed with carton, that puts everything under the `cwd`/local directory, so you will need to add `cwd`/local/bin to your path. If you install with cpanm without using sudo, it will install to the $HOME/perl5 directory, so you would add $HOME/perl5/bin to your path.

**Comment by devoid** [comment]
Rebased to d41ce5accf92f57dff64f019c5d33d4ba857bc2c <master>

**Comment by devoid** [comment]
I rebased this. So you should delete your local copy and check out a fresh copy.

**Comment by mdejongh** [comment]
I have done an "ms update" and now a "source bin/dev-env.sh" tells me:

-bash: setup-bash-complete: No such file or directory

So apparently I need to install something - but what?

On Tue, Sep 25, 2012 at 12:24 PM, Scott Devoid notifications@github.comwrote:

> 1. It's setup-bash-complete for BorneAgainSHell
> 2. If you installed with carton, that puts everything under the cwd/local
>    directory, so you will need to add cwd/local/bin to your path. If you
>    install with cpanm without using sudo, it will install to the $HOME/perl5
>    directory, so you would add $HOME/perl5/bin to your path.
>    
>    —
>    Reply to this email directly or view it on GitHubhttps://github.com/ModelSEED/ModelSEED/pull/82#issuecomment-8860476.

## 

Matt DeJongh, Ph.D.
Computer Science Department
Hope College, Holland, MI 49423
(616) 395-7429

**Comment by devoid** [comment]
Two things:
1. You'll need to add the perl5 binary directory to your path. This is
usually something like: $HOME/perl5/bin. setup-bash-complete is a perl
executable that is added when you install the Bash::Completion perl
module.
2. Make sure you're using the current master, as I stupidly did a
"minor code tidying" and didn't fully test it before adding it to the
pull request. That mistake is fixed as of
723ce3319df99d4b9adfecd3955f4b59cd5257bb
~ Scott

**Comment by mdejongh** [comment]
Thanks. I installed Bash::Completion using cpan and found the executable
here:

/usr/local/bin/setup-bash-complete

Looks like it's working now. Thanks,

Matt

On Tue, Oct 23, 2012 at 8:46 PM, Scott Devoid notifications@github.comwrote:

> Two things:
> 1. You'll need to add the perl5 binary directory to your path. This is
> usually something like: $HOME/perl5/bin. setup-bash-complete is a perl
> executable that is added when you install the Bash::Completion perl
> module.
> 2. Make sure you're using the current master, as I stupidly did a
> "minor code tidying" and didn't fully test it before adding it to the
> pull request. That mistake is fixed as of
> 723ce3319df99d4b9adfecd3955f4b59cd5257bb
> ~ Scott
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ModelSEED/ModelSEED/pull/82#issuecomment-9724008.

## 

Matt DeJongh, Ph.D.
Computer Science Department
Hope College, Holland, MI 49423
(616) 395-7429

**Pull request merged**
