### PR TITLE
Testing using Travis CI

### PR DESCRIPTION
**Pull request by devoid**
- Changes to code / test-suite to get unit tests passing in Travis CI

### CODE REVIEW

**Comment by devoid** [comment]
Yay, things are passing! @pfrybar I just need to hear from you regarding the change in KeyValueStore; then this is ready to merge.

For everyone's information, Travis CI is a public continuous integration service. It's integrated into Github so all commits are tested. Pull requests are annotated with the status of the most recent commit. I think it is exactly what we want. If we merge this, all future pull requests should have to pass test suites before merging with master.

**Comment by pfrybar** [comment]
Looks good to me. The changes to FileDB and KeyValueStore are fine. Are we ready to merge this?

**Comment by devoid** [comment]
Yees plz!

**Comment by mdejongh** [comment]
Do these fix the problems that Chris, Ric and I were seeing on Friday
(testing the modelseed build in KBase)?

On Tue, Oct 9, 2012 at 1:58 PM, Scott Devoid notifications@github.comwrote:

> Yees plz!
> 
> On Tue, Oct 9, 2012 at 12:56 PM, pfrybar notifications@github.com
> wrote:
> 
> > Looks good to me. The changes to FileDB and KeyValueStore are fine. Are
> > we
> > ready to merge this?
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/ModelSEED/ModelSEED/pull/107#issuecomment-9272196>.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ModelSEED/ModelSEED/pull/107#issuecomment-9272249.

## 

Matt DeJongh, Ph.D.
Computer Science Department
Hope College, Holland, MI 49423
(616) 395-7429

**Comment by devoid** [comment]
I'm not sure I understood where those problems were coming from. There's nothing in our code that would print a "Killed" message...nor have I seen that from the line in question, a call to `_encode` in KeyValueStore.

Basically I haven't been able to replicate the problem you described.

**Comment by mdejongh** [comment]
It's coming from the call encode_json($data);

Perhaps JSON isn't installed correctly in the kbase image.

Are you able to run the "Setup Test-Data" portion of the README.md on
kbase_v15 after a "make deploy"?

Matt

On Tue, Oct 9, 2012 at 3:59 PM, Scott Devoid notifications@github.comwrote:

> I'm not sure I understood where those problems were coming from. There's
> nothing in our code that would print a "Killed" message...nor have I seen
> that from the line in question, a call to _encode in KeyValueStore.
> 
> Basically I haven't been able to replicate the problem you described.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ModelSEED/ModelSEED/pull/107#issuecomment-9276695.

## 

Matt DeJongh, Ph.D.
Computer Science Department
Hope College, Holland, MI 49423
(616) 395-7429

**Comment by cshenry** [comment]
I'd like to know from Scott and Paul if they are able to replicate this problem... Matt and I were definately having this issue last Saturday.

**Comment by devoid** [comment]
I just ran it now on a fresh v15 instance. The only issue I ran into was forgetting to put the mongo data directory on `/mnt`. That meant the journal preallocation on startup took forever. Since I ran `nohup mongod &` I didn't see this, so the subsequent `stores add local --type mongo --host localhost` failed:

```
couldn't connect to server localhost:27017 at 
/kb/runtime/lib/perl5/site_perl/5.16.0/x86_64-linux/MongoDB/Connection.pm line 462.
```

But once the journal preallocation (mongod startup) was done everything worked fine:

```
root@devoid-v15:/kb/deployment# ms import biochemistry test
root@devoid-v15:/kb/deployment# ms import mapping test -b test -v
Will be saving to mapping/PUBLIC/test...
Fetching mapping from web...
Extracting...
Validating fetched mapping...
Saved mapping to mapping/PUBLIC/test!
```

**Comment by mdejongh** [comment]
weird - is there anything that depends on you being "devoid" (e.g., git
stuff, perl environment stuff, etc.?) I'll try over from the beginning when
I have a chance.
Matt

On Thu, Oct 11, 2012 at 4:01 PM, Scott Devoid notifications@github.comwrote:

> I just ran it now on a fresh v15 instance. The only issue I ran into was
> forgetting to put the mongo data directory on /mnt. That meant the
> journal preallocation on startup took forever. Since I ran nohup mongod &I didn't see this, so the subsequent stores
> add local --type mongo --host localhost failed:
> 
> couldn't connect to server localhost:27017 at
> /kb/runtime/lib/perl5/site_perl/5.16.0/x86_64-linux/MongoDB/Connection.pm line 462.
> 
> But once the journal preallocation (mongod startup) was done everything
> worked fine:
> 
> root@devoid-v15:/kb/deployment# ms import biochemistry test
> root@devoid-v15:/kb/deployment# ms import mapping test -b test -v
> Will be saving to mapping/PUBLIC/test...
> Fetching mapping from web...
> Extracting...
> Validating fetched mapping...
> Saved mapping to mapping/PUBLIC/test!
> 
>  —
> Reply to this email directly or view it on GitHubhttps://github.com/ModelSEED/ModelSEED/pull/107#issuecomment-9355537.

## 

Matt DeJongh, Ph.D.
Computer Science Department
Hope College, Holland, MI 49423
(616) 395-7429

**Comment by mdejongh** [comment]
It could be that my v15 image is too small (512MB ram). I'll re-run with
the same configuration Scott used.

Matt

On Thu, Oct 11, 2012 at 4:44 PM, Matt DeJongh dejongh@hope.edu wrote:

> weird - is there anything that depends on you being "devoid" (e.g., git
> stuff, perl environment stuff, etc.?) I'll try over from the beginning when
> I have a chance.
> Matt
> 
> On Thu, Oct 11, 2012 at 4:01 PM, Scott Devoid notifications@github.comwrote:
> 
> > I just ran it now on a fresh v15 instance. The only issue I ran into was
> > forgetting to put the mongo data directory on /mnt. That meant the
> > journal preallocation on startup took forever. Since I ran nohup mongod &I didn't see this, so the subsequent stores
> > add local --type mongo --host localhost failed:
> > 
> > couldn't connect to server localhost:27017 at
> > /kb/runtime/lib/perl5/site_perl/5.16.0/x86_64-linux/MongoDB/Connection.pm line 462.
> > 
> > But once the journal preallocation (mongod startup) was done everything
> > worked fine:
> > 
> > root@devoid-v15:/kb/deployment# ms import biochemistry test
> > root@devoid-v15:/kb/deployment# ms import mapping test -b test -v
> > Will be saving to mapping/PUBLIC/test...
> > Fetching mapping from web...
> > Extracting...
> > Validating fetched mapping...
> > Saved mapping to mapping/PUBLIC/test!
> > 
> >  —
> > Reply to this email directly or view it on GitHubhttps://github.com/ModelSEED/ModelSEED/pull/107#issuecomment-9355537.
> 
> ## 
> 
> Matt DeJongh, Ph.D.
> Computer Science Department
> Hope College, Holland, MI 49423
> (616) 395-7429

## 

Matt DeJongh, Ph.D.
Computer Science Department
Hope College, Holland, MI 49423
(616) 395-7429

**Comment by pfrybar** [comment]
Ahh yeah, in my experience we need more memory than that to import the
biochemistry. I've had issues with one of my virtual machines because it
was only 512MB. 1GB or more should work though.

**Comment by mdejongh** [comment]
OK, I got through the setup procedure this time, on the v1"small" image. So
the memory or disk space must have been the cause of my previous problem.

But now I am encountering this error when I try to import an annotation:

root@dejongh-kbase-v17:~/dev_container/modules/KBaseFBAModeling/scripts# ms
import annotation 83333.1 ecoli -mapping default -v
Will be saving to annotation/kbase/ecoli...
Will be saving to annotation/kbase/ecoli...
Fetching mapping/kbase/apping...
Getting annotation...
test3
Genome source is PUBSEED.
Can't locate object method "add" via package "ModelSEED::Store" at
/kb/deployment/lib/perl5/ModelSEED/MS/Factories/Annotation.pm line 228.

On Sat, Oct 13, 2012 at 10:13 AM, pfrybar notifications@github.com wrote:

> Ahh yeah, in my experience we need more memory than that to import the
> biochemistry. I've had issues with one of my virtual machines because it
> was only 512MB. 1GB or more should work though.
> 
> On Sat, Oct 13, 2012 at 8:57 AM, mdejongh notifications@github.com
> wrote:
> 
> > It could be that my v15 image is too small (512MB ram). I'll re-run with
> > the same configuration Scott used.
> > 
> > Matt
> > 
> > On Thu, Oct 11, 2012 at 4:44 PM, Matt DeJongh dejongh@hope.edu wrote:
> > 
> > > weird - is there anything that depends on you being "devoid" (e.g.,
> > > git
> > > stuff, perl environment stuff, etc.?) I'll try over from the beginning
> > > when
> > > I have a chance.
> > > Matt
> > > 
> > > On Thu, Oct 11, 2012 at 4:01 PM, Scott Devoid <
> > > notifications@github.com>wrote:
> > > 
> > > > I just ran it now on a fresh v15 instance. The only issue I ran into
> > > > was
> > > > forgetting to put the mongo data directory on /mnt. That meant the
> > > > journal preallocation on startup took forever. Since I ran nohup
> > > > mongod
> > > > &I didn't see this, so the subsequent stores
> > > > add local --type mongo --host localhost failed:
> > > > 
> > > > couldn't connect to server localhost:27017 at
> > 
> > /kb/runtime/lib/perl5/site_perl/5.16.0/x86_64-linux/MongoDB/Connection.pm
> > line 462.
> > 
> > > > But once the journal preallocation (mongod startup) was done
> > > > everything
> > > > worked fine:
> > > > 
> > > > root@devoid-v15:/kb/deployment# ms import biochemistry test
> > > > root@devoid-v15:/kb/deployment# ms import mapping test -b test -v
> > > > Will be saving to mapping/PUBLIC/test...
> > > > Fetching mapping from web...
> > > > Extracting...
> > > > Validating fetched mapping...
> > > > Saved mapping to mapping/PUBLIC/test!
> > > > 
> > > > —
> > > > Reply to this email directly or view it on GitHub<
> > > > https://github.com/ModelSEED/ModelSEED/pull/107#issuecomment-9355537>.
> > > 
> > > ## 
> > > 
> > > Matt DeJongh, Ph.D.
> > > Computer Science Department
> > > Hope College, Holland, MI 49423
> > > (616) 395-7429
> > 
> > ## 
> > 
> > Matt DeJongh, Ph.D.
> > Computer Science Department
> > Hope College, Holland, MI 49423
> > (616) 395-7429
> > 
> > —
> > 
> > Reply to this email directly or view it on GitHub<
> > https://github.com/ModelSEED/ModelSEED/pull/107#issuecomment-9404363>.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ModelSEED/ModelSEED/pull/107#issuecomment-9404488.

## 

Matt DeJongh, Ph.D.
Computer Science Department
Hope College, Holland, MI 49423
(616) 395-7429

**Pull request merged**
