### PR TITLE
Database: Ancestor & Descendant functions

### PR DESCRIPTION
**Pull request by devoid**
- Currently implemented reasonably efficent ancestor
  construction where the data is constructed at ancestor call-time
  if it does not alread exist. Should do it within save_data call
  but this makes it backwards compatible.
- Open Question: Do we return uuids or ModelSEED::Reference strings?
  UUIDs are easier, but reference strings are more explicit. If we
  use reference strings, do we return the originally passed refstring
  in the graph or a uuid-version of the string?

TODO:
- Implement decendant function at call-time
- Implement decendant functions in save_data
- Implement ancestor  functions in save_data

### CODE REVIEW

**Comment by pfrybar** [comment]
Can you explain how this new ancestor/descendant system works? Currently an object stores it's ancestors directly. It looks like you're now storing both the ancestors and descendants in a different data structure in Mongo? Should we remove the "ancestor_uuids" attribute in the object itself?

**Comment by devoid** [comment]
Currently we're storing the parent UUIDs in the "ancestor_uuids" field ( naming is a bit off because there's already a "parent" function that returns the parent with respect to the object hierarchy.

These functions add a collection with the entries like the following:

``` json
{
    "uuid" : "$uuid",
    "ancestors" : [ "$uuid", "$uuid", ... ],
    "descendants" : [ "$uuid", "$uuid", ... ],
    "ancestor_graph" : {
        "$child" : [ "$parent" ],
    },
    "descendant_graph" : {
        "$parent" : [ "$child", "$child" ],
    }
}
```

**Comment by pfrybar** [comment]
What about merges and splits? How would the ancestor/descendant arrays represent these cases?

**Comment by devoid** [comment]
If C merges data from A and B, it's "ancestors" array will contain both A and B.
A and B's descendant arrays will both contain "C".

If the graph looks like this:

```
A ----> D -> C
B -----------^
```

C's ancestors will contain A, B and D.

**Comment by pfrybar** [comment]
Alright, so there is no structure to the ancestor array? If ancestors is: ['A', 'B', 'D'] there is no way to see that C is a merge of B and D.

**Comment by devoid** [comment]
That's in the ancestor_graph hash.
{
    C : [ "B", "D" ],
    D : [ "A" ],
    B : [ ],
    A : [ ],
}

**Comment by pfrybar** [comment]
Ok, so the ordering doesn't matter for ancestors and descendants, correct? Just want to make sure since I'm writing the code for FileDB.

**Comment by devoid** [comment]
That's correct.

**Comment by pfrybar** [comment]
So how does this look for the following scenario? (I replaced the uuids with #'s to make it more readable)

```
4-->3-->2-->1

{
  "1": {
    "ancestor_graph": {
      "4": [],
      "1": [
        "2"
      ],
      "2": [
        "3"
      ],
      "3": [
        "4"
      ]
    },
    "descendants": [],
    "ancestors": [
      "2",
      "3",
      "4"
    ],
    "descendant_graph": {
      "1": []
    }
  },
  "2": {
    "ancestor_graph": {
      "4": [],
      "2": [
        "3"
      ],
      "3": [
        "4"
      ]
    },
    "descendants": [
      "1"
    ],
    "ancestors": [
      "3",
      "4"
    ],
    "descendant_graph": {
      "1": [],
      "2": [
        "1"
      ]
    }
  },
  "3": {
    "ancestor_graph": {
      "4": [],
      "3": [
        "4"
      ]
    },
    "descendants": [
      "2",
      "1"
    ],
    "ancestors": [
      "4"
    ],
    "descendant_graph": {
      "1": [],
      "2": [
        "1"
      ],
      "3": [
        "2"
      ]
    }
  },
  "4": {
    "ancestor_graph": {
      "4": []
    },
    "descendants": [
      "3",
      "2",
      "1"
    ],
    "ancestors": [],
    "descendant_graph": {
      "4": [
        "3"
      ],
      "1": [],
      "2": [
        "1"
      ],
      "3": [
        "2"
      ]
    }
  }
}
```

**Comment by pfrybar** [comment]
Also, are you handling the special merge case in your Mongo code?

**Comment by devoid** [comment]
I think that's right. The base case, an object "$uuid" with no ancestors or descendant is:

``` json
{
    "uuid" : "$uuid",
    "ancestors" : [],
    "descendants" : [],
    "ancestor_graph" : {
        "$uuid" : []
    },
    "descendant_graph" : {
        "$uuid" : []
    }
}
```

You're collapsing everything into a single "object of objects". The collection contains a document for each `$uuid`. Obviously that is an implementation detail on my part, but the functions should return the value for the `ancestor`, `ancestor_graph`, etc. fields for the single object.

For the special case... do you mean calling save_data with a `{ is_merge => 1 }` config? Yea, I'm assuming that the "ancestor_uuids" field is correct and contains all of the direct parents. So I'm adding that to the new object's "ancestors" and treating it like a merge.

**Comment by devoid** [comment]
If you're having trouble (which I can totally understand, it's not well documented), I can try to clean up my tests cases to make those more clear. Would that help?

**Comment by pfrybar** [comment]
No, it's fine, I understand the functions. I'm just trying to make sure we get this right on the first try, otherwise it'll be a pain to fix.

What I'm trying to figure out now is the 'is_merge' case. Say we have this scenario:

```
A ---> B ---> C ---> D
E ------------^
```

B's ancestor_uuids should be ['A'], C's should be ['B', 'E'] and D's should be ['C']. However I don't think this code accomplishes that (MongoDBSimple.pm, line 112):

```
unless($config->{is_merge}) {
    $object->{ancestor_uuids} = [ $oldUUID ];
}
```

With this code, C's ancestor_uuids will be ['A']. Maybe I am missing something here.

**Comment by devoid** [comment]
If `is_merge` is set, we assume that the uuids in `ancestor_uuids` are
complete, so we don't update them. We additionally assume that the user
issued a new uuid (the save will fail if that's not the case). In other
words, we assume that the user does:

``` perl
my $store, $ref; # store and ref stuff
my $other, $obj; # two objects we're merging
# Do other parts of the merge...
$obj->ancestor_uuids([ $obj->uuid, $other->uuid ]);
$obj->uuid(Data::UUID->new->create_str);
$store->save_object($ref, $obj, { is_merge => 1 });
```

**Pull request merged**
